swagger: '2.0'
x-id:
  - reitit.swagger/default
info:
  title: Deferred deep linking API
  version: 0.1-beta
paths:
  '/v1.0/ios/{app_id}':
    post:
      responses:
        '200':
          schema:
            type: object
            properties:
              found:
                type: boolean
              click_event:
                type: object
                properties:
                  af_sub1:
                    type: string
                    x-nullable: true
                  campaign_id:
                    type: string
                    x-nullable: true
                  custom_params:
                    type: object
                    properties: {}
                    title: custom_params
                  campaign_type:
                    enum:
                      - retargeting
                      - user_acquisition
                    type: string
                  timestamp:
                    type: string
                    x-nullable: true
                  match_type:
                    enum:
                      - referrer
                      - id_matching
                      - srn
                      - fingerprinting
                    type: string
                  af_sub5:
                    type: string
                    x-nullable: true
                  media_source:
                    type: string
                    x-nullable: true
                  campaign:
                    type: string
                    x-nullable: true
                  af_sub4:
                    type: string
                    x-nullable: true
                  click_http_referrer:
                    type: string
                    x-nullable: true
                  af_sub2:
                    type: string
                    x-nullable: true
                  af_sub3:
                    type: string
                    x-nullable: true
                required:
                  - timestamp
                  - match_type
                  - click_http_referrer
                  - media_source
                  - campaign
                  - campaign_id
                  - campaign_type
                  - af_sub1
                  - af_sub2
                  - af_sub3
                  - af_sub4
                  - af_sub5
                  - custom_params
                title: click_event
            required:
              - found
              - click_event
            title: response
          description: ''
      produces:
        - application/json
        - application/transit+msgpack
        - application/transit+json
        - application/edn
      consumes:
        - application/json
        - application/transit+msgpack
        - application/transit+json
        - application/edn
      parameters:
        - in: path
          name: app_id
          description: ''
          type: string
          required: true
        - in: query
          name: af_sig
          description: ''
          type: string
          required: true
        - in: query
          name: sdk_version
          description: ''
          type: string
          required: true
        - in: body
          name: sdk_ios_request
          description: ''
          required: true
          schema:
            type: object
            properties:
              idfv:
                type: object
                properties:
                  type:
                    enum:
                      - unhashed
                      - sha1
                      - md5
                    type: string
                  value:
                    type: string
                required:
                  - type
                  - value
                title: idfv
              lang:
                type: string
              att_status:
                type: integer
                format: int64
              is_first:
                type: boolean
              os:
                type: string
              timestamp: {}
              type:
                type: string
              idfa:
                type: object
                properties:
                  type:
                    enum:
                      - unhashed
                      - sha1
                      - md5
                    type: string
                  value:
                    type: string
                required:
                  - type
                  - value
                title: idfa
              sharing_filter:
                type: string
                x-anyOf:
                  - type: string
                  - x-allOf:
                      - {}
                      - type: array
            required:
              - is_first
              - lang
              - os
              - timestamp
              - type
            title: sdk_ios_request
      tags:
        - ddl
      summary: Deferred deep link for IOS
  '/v1.0/android/{app_id}':
    post:
      responses:
        '200':
          schema:
            type: object
            properties:
              found:
                type: boolean
              click_event:
                type: object
                properties:
                  af_sub1:
                    type: string
                    x-nullable: true
                  campaign_id:
                    type: string
                    x-nullable: true
                  custom_params:
                    type: object
                    properties: {}
                    title: custom_params
                  campaign_type:
                    enum:
                      - retargeting
                      - user_acquisition
                    type: string
                  timestamp:
                    type: string
                    x-nullable: true
                  match_type:
                    enum:
                      - referrer
                      - id_matching
                      - srn
                      - fingerprinting
                    type: string
                  af_sub5:
                    type: string
                    x-nullable: true
                  media_source:
                    type: string
                    x-nullable: true
                  campaign:
                    type: string
                    x-nullable: true
                  af_sub4:
                    type: string
                    x-nullable: true
                  click_http_referrer:
                    type: string
                    x-nullable: true
                  af_sub2:
                    type: string
                    x-nullable: true
                  af_sub3:
                    type: string
                    x-nullable: true
                required:
                  - timestamp
                  - match_type
                  - click_http_referrer
                  - media_source
                  - campaign
                  - campaign_id
                  - campaign_type
                  - af_sub1
                  - af_sub2
                  - af_sub3
                  - af_sub4
                  - af_sub5
                  - custom_params
                title: click_event
            required:
              - found
              - click_event
            title: response
          description: ''
      produces:
        - application/json
        - application/transit+msgpack
        - application/transit+json
        - application/edn
      consumes:
        - application/json
        - application/transit+msgpack
        - application/transit+json
        - application/edn
      parameters:
        - in: path
          name: app_id
          description: ''
          type: string
          required: true
        - in: query
          name: af_sig
          description: ''
          type: string
          required: true
        - in: query
          name: sdk_version
          description: ''
          type: string
          required: true
        - in: body
          name: sdk_android_request
          description: ''
          required: true
          schema:
            type: object
            properties:
              referrers:
                type: array
                items:
                  type: object
                  properties:
                    source:
                      type: string
                    value:
                      type: string
                  required:
                    - source
                    - value
                  title: referrer
              lang:
                type: string
              is_first:
                type: boolean
              os:
                type: string
              timestamp: {}
              oaid:
                type: object
                properties:
                  type:
                    enum:
                      - unhashed
                      - sha1
                      - md5
                    type: string
                  value:
                    type: string
                required:
                  - type
                  - value
                title: request-spec/oaid
              type:
                type: string
              gaid:
                type: object
                properties:
                  type:
                    enum:
                      - unhashed
                      - sha1
                      - md5
                    type: string
                  value:
                    type: string
                required:
                  - type
                  - value
                title: request-spec/gaid
              sharing_filter:
                type: string
                x-anyOf:
                  - type: string
                  - x-allOf:
                      - {}
                      - type: array
            required:
              - is_first
              - lang
              - os
              - timestamp
              - type
            title: sdk_android_request
      tags:
        - ddl
      summary: Deferred deep link for Android
